source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'myfirstcocoapod_Example', :exclusive => true do
  pod 'myfirstcocoapod', :path => '../'
end

target 'myfirstcocoapod_Tests', :exclusive => true do
  pod 'myfirstcocoapod', :path => '../'

  
end
